failedOnly: false
# showOrder: [docker, sysinfo]
colDef:
  - [sysinfo]
  - [updates]
  - [docker, podman]
  - [systemd]
  - [cpu, disk]
  - [zfs]
  - [btrfs]
colPad: 10
updates:
  header: [0, 3]
  content: [1, 0]
  show: false
  file: /tmp/go-check-updates.yaml
  check: 24h
sysinfo:
  header: [0, 4]
systemd:
  header: [0, 3]
  content: [2, 1]
  hideExt: true
  inactiveOK: false
  units:
    - nginx.service
    - postgresql-12.service
    - smb.service
    - libvirtd.service
    - firewalld.service
    - zfs-automount.service
    - zfs-mount.service
    - check-nginx-modules.service
    - onedrive@andrei.service
    # - fictional.service
docker:
  useExec: false
  header: [0, 4]
  content: [2, 1]
  ignore:
    - code-server
podman:
  includeSudo: true
  header: [0, 4]
  content: [0, 1]
disk:
  useSys: true
  header: [0, 1]
  content: [6, 1]
  warn: 40
  crit: 50
cpu:
  useExec: false
  header: [0, 2]
  content: [2, 2]
  warn: 70
  crit: 90
zfs:
  failedOnly: false
  header: [0, 7]
  content: [1, 5]
  warn: 70
  crit: 90
