global:
  warnings_only: true
  show_order: []
  col_def:
    - [sysinfo]
    - [updates]
    - [docker, podman]
    - [systemd]
    - [cpu, disk]
    - [zfs]
    - [btrfs]
  col_pad: 10
btrfs:
  warnings_only: false
  pad_header: [0, 5]
  pad_content: [1, 3]
  warn: 70
  crit: 90
cpu:
  pad_header: [0, 2]
  pad_content: [2, 2]
  warn: 70
  crit: 90
  use_exec: false
disk:
  pad_header: [0, 1]
  pad_content: [6, 1]
  warn: 40
  crit: 50
  use_sys: true
docker:
  pad_header: [0, 4]
  pad_content: [2, 1]
  use_exec: false
  ignore:
  - code-server
podman:
  pad_header: [0, 4]
  pad_content: [0, 1]
  sudo: false
  include_sudo: true
sysinfo:
  pad_header: [0, 4]
  pad_content: [0, 0]
systemd:
  warnings_only: false
  pad_header: [0, 3]
  pad_content: [2, 1]
  units:
  - nginx.service
  - smb.service
  - libvirtd.service
  - firewalld.service
  - fictional.service
  - tmp.mount
  hide_ext: true
  inactive_ok: false
  show_failed: true
updates:
  pad_header: [0, 4]
  pad_content: [0, 1]
  show: false
  file: /tmp/go-check-updates.yaml
zfs:
  warnings_only: false
  pad_header: [0, 7]
  pad_content: [1, 5]
  warn: 70
  crit: 90
