failedOnly: true
updates:
  header: [0, 3]
  content: [1, 0]
  show: false
  file: /tmp/go-check-updates.yaml
  check: 24h
sysinfo:
  header: [0, 4]
systemd:
  header: [0, 3]
  content: [2, 1]
  units:
    - nginx.service
    - postgresql-12.service
    - smb.service
    - libvirtd.service
    - firewalld.service
    - zfs-automount.service
    - zfs-mount.service
    - check-nginx-modules.service
    # - fictional.service
docker:
  header: [0, 4]
  content: [2, 1]
  ignore:
    - code-server
disk:
  header: [0, 1]
  content: [1, 1]
  warn: 40
  crit: 50
cpu:
  header: [0, 2]
  content: [2, 2]
  warn: 70
  crit: 90
zfs:
  failedOnly: false
  header: [0, 7]
  content: [1, 5]
  warn: 70
  crit: 90
